### ISSUE TITLE
What packages are needed to run the new imports correctly?

### ISSUE THREAD

**Issue by alvincrespo** [ember-cli/ember-modules-codemod#14]
I’m running into an issue, where after installing a project that has run `ember-modules-codemod` I’m unable to run the application because of this error: `Uncaught Error: Could not find module @ember/application imported from 'my-app/app'`

```
➜  frontend git:(master) ✗ ember -v
ember-cli: 2.13.1
node: 7.10.0
os: darwin x64
```

**Comment by Turbo87** [comment]
either [ember-new-modules-shim](https://github.com/DockYard/ember-new-modules-shim) or [ember-cli-shims](https://github.com/ember-cli/ember-cli-shims) once https://github.com/ember-cli/ember-cli-shims/pull/92 is merged and released.

**Comment by Turbo87** [comment]
the recommended way will be to install `ember-cli-babel` at version 6.5.0 or above
