### ISSUE TITLE
Correct place to report a bug?

### ISSUE THREAD

**Issue by toranb** [ember-cli/ember-modules-codemod#23]
@rwjblue I really like this project :) and greatly appreciate your involvement to move the community forward!

I started converting one of my addons today and found that when I destructure assert from `@ember/debug` the compiled output omits it for some odd reason. When I did some source diving I found what looks like a missing dependency (shown in the snippet at the bottom of this issue).

`import { assert } from '@ember/debug';`

```js
enifed('ember-debug/index', ['exports', 'ember/features', 'ember-environment', 'ember-console', 'ember-debug/testing', 'ember-debug/error', 'ember-debug/features', 'ember-debug/deprecate', 'ember-debug/warn'], function (exports, _emberFeatures, _emberEnvironment, _emberConsole, _emberDebugTesting, _emberDebugError, _emberDebugFeatures, _emberDebugDeprecate, _emberDebugWarn) {
  'use strict';

  exports._warnIfUsingStrippedFeatureFlags = _warnIfUsingStrippedFeatureFlags;
  exports.getDebugFunction = getDebugFunction;
  exports.setDebugFunction = setDebugFunction;
  exports.assert = assert;
  exports.info = info;
  exports.warn = warn;
```

^^ In the above I see how warn would be injected/ and then wired up to the export but ... I don't see the same for assert. If this is the root cause, what project (or sub project) should land the PR to fix this so others can destructure assert without issue? Thank you in advance!

**Comment by rwjblue** [comment]
Firstly, the snippet you pasted was from Embers internal module registry (which is completely isolated from your apps modules).

A few things to review:

* https://github.com/ember-cli/rfcs/pull/50
* https://github.com/babel/ember-cli-babel/blob/master/README.md#debug-tooling
* http://rwjblue.com/2017/05/01/enabling-debug-code-stripping/

_tldr;_ The `assert` import is supposed to be stripped in production builds. You may or may not have an issue, but we need to understand the actual circumstances a bit more first to diagnose. 

Also, this will likely end up being an issue over on ember-cli-babel (not the "once and done" codemod).

**Comment by rwjblue** [comment]
Closing for now, hopefully my answer was helpful...

**Comment by toranb** [comment]
@rwjblue yup -thanks for the direction. At this time I think I'll need to open an issue w/ ember-cli-babel describing my use case (of assert) to better understand the path forward
