### ISSUE TITLE
Ember.Test.registerAsyncHelper not rewritten

### ISSUE THREAD

**Issue by bcardarella** [ember-cli/ember-modules-codemod#41]
I'll assume if the codemod doesn't rewrite that the function isn't being exposed as import yet. This function is used by ember-responsive: https://github.com/freshbooks/ember-responsive/blob/master/blueprints/ember-responsive/files/tests/helpers/responsive.js#L48

**Comment by rwjblue** [comment]
I believe it is updated in the ember-rfc176-data repo, but we likely need to bump the dep here and re-release...

**Comment by sduquej** [comment]
I think this was fixed in https://github.com/ember-cli/ember-modules-codemod/releases/tag/v0.2.4. Can this issue be closed?
