### ISSUE TITLE
Final Boss test failure on Windows (line endings)

### ISSUE THREAD

**Issue by XaserAcheron** [ember-cli/ember-modules-codemod#44]
A peculiarity I noticed on Windows: the `final-boss` test fails due to line ending shenanigans:

![2017-09-19 10_21_38-administrator_ cmd](https://user-images.githubusercontent.com/4601589/30601228-0d5f21ec-9d27-11e7-9eb3-c1e9130866d0.png)

The `final-boss.output.js` fixture uses `\r\n` everywhere, but the output generated by `ember-modules-codemod` is using `\n`s on those three lines for some reason. For grins, I hex edited the output.js fixture to change those 3 lines to `n`s, and the test passes, but this it obviously non-ideal. ;)

I say this is Windows-specific since Travis seems to be pretty chill with the current state of things, but of course that means it's probably on me to try and come up with a solution given how rare we `ember-windows` folk seem to be. Welp.

**Comment by kellyselden** [comment]
The last step in the codemod before saving to disk, you could do:

```js
const EOL = require('os').EOL;

fs.writeFileSync('output.js', str.replace(/\n/g, EOL));
```

like we do [here](https://github.com/kellyselden/ember-cli-update/blob/6ba4c840002cff5935067879b1a76f011db0c694/src/auto-merge-package-json.js#L65). This would be a noop for Unix.

**Comment by ro0gr** [comment]
Do I understand correct that currently `ember-modules-codemod` outputs different line endings for linux vs windows? If so running a codemod on windows will violate `ember-cli`'s
 [editorconfig](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/.editorconfig#L9) from the app blueprint.

Or is it just a test setup issue?

**Comment by XaserAcheron** [comment]
The codemod itself doesn't touch lines it doesn't care about, fortunately, even in Windows-land.

Thinking on it a bit, the likely culprit means there's something inaccurate in my opening post -- I'll bet the source _doesn't_ use `\r\n` at all; just `\n`... because Git is configured on my system to convert the line endings to Windows' format. Oy vey -- I really don't know why that's considered the "recommended" approach with Git; you'd think we'd have this problem licked in 2017. ;)

**Comment by ro0gr** [comment]
@XaserAcheron maybe we can force autocrlf=false on repository level somehow? If it's possible does it sound like a sufficient solution?

**Comment by kellyselden** [comment]
Try this https://github.com/kellyselden/ember-cli-update/blob/master/.gitattributes

**Comment by ro0gr** [comment]
thanks @kellyselden

**Comment by XaserAcheron** [comment]
That'd do it for the unit tests (and is probably a good call for everyone's sanity), but there's a distinct-but-related issue: when actually running the codemod, it's going to insert `\n`s, resulting in mixed line endings in files that already use `\r\n`.

...but thinking on it, that's probably best left for another time, if at all. That really is a lot of effort spent fixing something that's (IMO) super-minor. The important bit is that the tests work, so +1 for @ro0gr's PR (#45) and calling this done-until-further-notice.

**Comment by rwjblue** [comment]
I think this is fixed by #45 now, can you confirm and close?

**Comment by XaserAcheron** [comment]
Huh -- now I'm getting the literal opposite problem: _every_ test is failing, with every line flagged as different except the ones in the final boss test that were problematic before. :P

The .gitattrbutes patch did what it was supposed to -- my local files on a freshly cloned repo have `\n`s, but the codemod is still spitting out `\r\n`s. I did some searching and found [this line](https://github.com/benjamn/recast/blob/c78b4cd9ddf1ba45f6696f6b6c0534f962693bfb/lib/options.js#L21) in `recast`; looks like it's unconditionally using the OS-defined line endings if nothing else is specified, and I'm not seeing anything in the codemod that's overriding it.

Insert audible sigh here, I suppose.

**Comment by ro0gr** [comment]
the same issue. I've just tried #47 to [pass option to recast](https://github.com/facebook/jscodeshift#passing-options-to-recast) and seems like it fixes the issue

**Comment by XaserAcheron** [comment]
I think it may make sense to just do the inverse of #47 and convert all hardcoded `\n`s with `require('os').EOL` -- that'll keep things consistent with `recast` at least, and probably resolve most of the issues for folks (since "convert to CRLF on checkout" is the Git default on windows).

It's a step forward at least.

**Comment by ro0gr** [comment]
> I think it may make sense to just do the inverse of #47 and convert all hardcoded \ns with require('os').EOL -- that'll keep things consistent with recast

isn't it the same as it was before #47. We did't specify `lineTerminator` and that was the reason why all the tests failed on windows. I think it's still important to make sure that we have consistent line endings in the fixtures in order to make testing deterministic.

What if we try to detect an actual source file line ending before the transform? I think detection is not a big deal but seems like there are few caveats:
 - it looks like recast supports single `lineTerminator` per invocation so it would be impossible to handle mixed line endings in the same file. Don't think it's a real issue
 - it complicates testing a little bit

**Comment by XaserAcheron** [comment]
> isn't it the same as it was before #47.

Not quite. The "before scenario" on Windows goes something like:
- Git (assuming recommended settings) uses the OS default (`\r\n`)
- `recast` uses the OS default (`\r\n`)
- `ember-modules-codemod` always uses `\n` (whoops! inconsistency happens)

I'm suggesting making the codemod use the OS default (`\r\n` on Windows) for starters, since that's a step toward keeping things in sync (leaving the user's Git settings as the wildcard). Doing some file detection and/or `.editorconfig` checking would close the gap even further, so that's a great next step. 👍

**Comment by ro0gr** [comment]
When running `ember new appname` git settings are not taken into account. 
I've just checked freshly generated app and all the files have lf line ending. 

So I think if we follow recast default we may introduce inconsistency rather than fix it.

**Comment by ro0gr** [comment]
My point is that we need to consider git part only for fixtures consistency purpose. 
In the transformation itself we should not take git into account and detect an actual source file line endings. That's how I understand the situation at least..

**Comment by ro0gr** [comment]
@XaserAcheron I'm going to make one more pr(with auto-detection) if you don't have strong objections. 
I hope this way we can validate an approach at least

**Comment by XaserAcheron** [comment]
> When running ember new appname git settings are not taken into account.
> I've just checked freshly generated app and all the files have lf line endings.

It turns to `\r\n` when the file gets modified by Git (e.g. checking out a different version when switching branches and whatnot), though that indeed means a fresh, never-modified file will retain its LFs as long as Git (or some other editor) never messes with it. I suppose that means all bets are off for original authors of an app/addon. It's edge cases all the way down. :P

Auto-detection ought to make this all moot anyway. Go for it!

**Comment by ro0gr** [comment]
>> never-modified file will retain its LFs as long as Git (or some other editor) never messes with it

of course you are right

**Comment by XaserAcheron** [comment]
Confirmed that #48 fixes all my nutty Windows gripes. ;)
