### ISSUE TITLE
Missed destructuring of old 'rsvp' shim

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-modules-codemod#78]
If you use the old shim like:

```js
import RSVP from 'rsvp';

const { resolve } = RSVP;
```

It is not caught by the codemod. Is that something worth supporting? Please close if it is out of scope.

**Comment by kellyselden** [comment]
It correctly converts:

```js
import Ember from 'ember';

const { RSVP: { resolve } } = Ember;
```

into

```js
import { resolve } from 'rsvp';
```

**Comment by rwjblue** [comment]
Seems fine to support I think.  Not sure what changes would be needed....

**Comment by jordansaints** [comment]
As another data point, I had the same issue in my repos. It seems to apply to all nested destructures which are been broken across multiple statements.

A simplified example:

Before codemod:
```js
const { computed } = Ember;
const { oneWay } = computed;
```

After codemod:
```js
import { computed } from '@ember/object';

const { oneWay } = computed;
```

Note the `const { oneWay } = computed;` is ignored by the codemod.

I can't speak to how common this pattern elsewhere, but in our team, we preferred this format over `const { a: { b } } = c;` for readability, and therefore have it in lots of places within our code.

**Comment by rwjblue** [comment]
Yep. Totally agree with you there (multi-level destructures really hurt my head 🤕). This just needs someone to care enough to put in the time to fix.  Anyone feel like making life better for everyone else? 🤗

**Comment by danwenzel** [comment]
@jordansaints @rwjblue - I opened a PR to fix the multi-statement problem that Jordan brought up above: https://github.com/ember-cli/ember-modules-codemod/pull/81

The RSVP case will be a little bit trickier, as it doesn't come from an Ember global.
