### ISSUE TITLE
Import alphabetization is not honored

### ISSUE THREAD

**Issue by ghaagsma** [ember-cli/ember-modules-codemod#86]
My product has a strict lint configuration, including the requirement that imports are sorted alphabetically (case-sensitive, multiple before single). Is there a way to configure this module to honor the import order specified in the `.eslintrc.js` configuration for the project?

**Comment by kellyselden** [comment]
Does that rule have an autofix? Can you run `eslint --fix` after the codemod?

**Comment by ghaagsma** [comment]
This rule does not have an autofix; however, I was able to resolve my situation using a combination of [eslint-plugin-sort-imports-es6-autofix](https://github.com/marudor/eslint-plugin-sort-imports-es6-autofix) and the fix provided in the comments of [this](https://github.com/marudor/eslint-plugin-sort-imports-es6-autofix/issues/6) issue. Ended up being quite inconvenient, but perhaps this is a linting issue rather than `ember-modules-codemod` issue.

**Comment by kellyselden** [comment]
Yep. This project assuming you have eslint is not ideal.

**Comment by kellyselden** [comment]
Thanks for the issue though.
