### ISSUE TITLE
Can I run codemod on a directory or does it need to run on the whole project?

### ISSUE THREAD

**Issue by sarbbottam** [ember-cli/ember-modules-codemod#88]
```
$ cd path/to/app/adapters
$ npx ember-modules-codemod
npx: installed 295 in 15.763s
It doesn't look like you're inside an Ember app. I couldn't find a package.json at 
```

I initially ran code mode on the whole project but ended up breaking the build in production mode.
Thus wanted to run the codemod on a limited number of files.

Is there any way to do that?

**Comment by rwjblue** [comment]
Fixed by https://github.com/ember-cli/ember-modules-codemod/pull/32
